### ISSUE TITLE
Can you make an application using current version of Ext JS (6.5.3.57)?

### ISSUE THREAD

**Issue by donhuvy** [ekojs/Web-Desktop#1]
As you knew, you are using Ext JS 4. Current version is 6.5.3.57. Can you make an application using current version of Ext JS (6.5.3.57)?

Thank you!

Happy coding!

**Comment by ekojs** [comment]
I stop using ExtJS above 4. Because License matter. The Open source license just until ExtJS 4, so my application still based on ExtJS 4.

**Comment by donhuvy** [comment]
thank you!
